name: calendario_academico
description: "UniCal - Gesti√≥n de semestres, materias y notas"
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Routing
  go_router: ^15.1.2
  
  # Utils
  connectivity_plus: ^6.1.4
  uuid: ^4.5.1
  intl: ^0.20.2
  equatable: ^2.0.7
  
  # UI Components
  flutter_local_notifications: ^20.0.0
  table_calendar: ^3.1.3
  local_notifier: ^0.1.6
  timezone: ^0.10.1
  universal_html: ^2.3.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.4
  share_plus: ^12.0.1
  
  # Version & Updates
  package_info_plus: ^8.0.0
  url_launcher: ^6.2.5
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#6B7FD7"
  adaptive_icon_foreground: "assets/images/logo.png"

flutter:
  uses-material-design: true
